# Generated by Django 4.0.2 on 2022-04-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hryvnia',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, null=True),
        ),
    ]
