# Generated by Django 4.0.2 on 2022-04-23 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_category_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.new'),
        ),
    ]
