# Generated by Django 4.0.2 on 2022-04-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_category_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short',
            field=models.CharField(default='', max_length=50),
        ),
    ]
