# Generated by Django 4.0.2 on 2022-04-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ru_title',
            field=models.CharField(default=models.CharField(max_length=255), max_length=255),
        ),
    ]
