# Generated by Django 4.0.2 on 2022-04-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='ru_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
